name: Update github pages

on: [push]

jobs:
  update-pages-repo:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: mkdir dist
      - run: echo "$(date)" > dist/${GITHUB_REF##*/}.md
      - run: cat dist/${GITHUB_REF##*/}.md

      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - uses: actions/checkout@v2
        with:
          repository: illiiiillllilii/illiiiillllilii.github.io
          path: ./PAGES
          token: ${{ secrets.TALY_GH_TOKEN }}

      - run: |
          rm -rf ./PAGES/${GITHUB_REF##*/}
          mkdir -p ./PAGES/${GITHUB_REF##*/}
          cp -R dist/ ./PAGES/${GITHUB_REF##*/}
          cd ./PAGES
          git add .
          git commit -m "chore: add new dist folder"
          git push
