name: Update github pages

on: [push]

jobs:
  update-pages-repo:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: mkdir dist
      - run: echo "$(date)" > dist/${GITHUB_REF##*/}.md
      - run: cat dist/${GITHUB_REF##*/}.md

      - run: |
          git clone --depth 1 https://github.com/illiiiillllilii/illiiiillllilii.github.io.git PAGES
          rm -rf PAGES/${GITHUB_REF##*/}
          mkdir -p PAGES/${GITHUB_REF##*/}
          cp -R dist/ PAGES/${GITHUB_REF##*/}
          cd PAGES
          git add .
          git commit -m "chore: add new dist folder"
          git push
