name: GitHub Pages deploy

on: [push]

jobs:
  update-pages-repo:
    env:
      BRANCH: ${GITHUB_REF##*/}
      DEPLOY_LINK: https://illiiiillllilii.github.io/${ GITHUB_REF##*/ }/index.html
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: mkdir dist
      - run: echo "$(date)" > dist/index.md
      - run: cat dist/index.md

      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - uses: actions/checkout@v2
        with:
          repository: illiiiillllilii/illiiiillllilii.github.io
          path: ./PAGES
          token: ${{ secrets.TALY_GH_TOKEN }}

      - run: |
          rm -rf ./PAGES/${{ env.BRANCH }}
          mkdir -p ./PAGES/${{ env.BRANCH }}
          cp -R dist/* ./PAGES/${{ env.BRANCH }}
          cd ./PAGES
          git add .
          git commit -m "chore: add new dist folder"
          git push

      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: "success"
          url: ${{ DEPLOY_LINK }}
          description: "Successfully deployed to pages"
          name: "GitHub Pages deploy"
