name: Update github pages

on: [push]

jobs:
  update-pages-repo:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "$(date)" > ${{GITHUB_REF##*/}}.md

      - run: cat ${{GITHUB_REF##*/}}.md

      - run: ls -la
